### ISSUE TITLE
very dangerous, as there is no security check

### ISSUE THREAD

**Issue by kiosan** [RubyForceTeam/recipes#22]
https://github.com/RubyForceTeam/recipes/blob/d040dbd7132530eb8ba9ff33381489faecb8b41b/app/controllers/recipes_controller.rb#L45

could be fixed by adding:

`current_user.receipts.find(prams[:id]).destroy`

this will allow user to delete only his own receipt

**Comment by otkachyk** [comment]
Fixed, will keep in mind, thank you.
